server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: fritzbox
    static_configs:
      - targets:
          - localhost
        labels:
          job: fritzbox
          __path__: /path/to/your/fritzLog.jsonl
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            source: source
            message: message
            date: labels.date
            time: labels.time
            code: labels.code
            component: labels.component
      - timestamp:
          source: timestamp
          format: Unix
      - labels:
          level:
          source:
          date:
          code:
          component:
          severity:
      - output:
          source: message
